### ISSUE TITLE
Unable to write in text box

### ISSUE THREAD

**Issue by Flintwyrm** [hitcherland/FoundryVTT-Heart#1]
Some of the text boxes on the sheet cant be writt
![Screenshot_2055](https://user-images.githubusercontent.com/60701064/122243107-d8ee2e80-ce91-11eb-8dff-ff493757afc4.png)
en on due to spacing

**Comment by hitcherland** [comment]
Thanks for raising this! Should be fixed in 0.2.2 which is now available.
