### ISSUE TITLE
Translation to spanish

### ISSUE THREAD

**Issue by jesberpen** [hitcherland/FoundryVTT-Heart#12]
Hello, I have done a es.json file for the game to be in spanish, but I'm not sure the best way to add it to your system, I'm not super well versed with github.

**Comment by jesberpen** [comment]
Nevermind, I found a guide and I think I did it correctly, let me know otherwise! You should have a pull request now with the translation.

**Comment by hitcherland** [comment]
Oh wow, thanks! You have done the technically correct thing, but I'm using a weird branching thing to help me manage things., which is going to make this kinda awkward. When I have a moment, I'll backport it to the development branch. How would you like to be credited? I'll probably add a new release note, as well as including our username/name in the source.

**Comment by jesberpen** [comment]
Hi, awesome, thanks a lot! Just the username is fine :)
For future updates let me know how you want to manage it then, I can adapt :), I will probably start seeing some misspellings or tweak some words as I start using it. I've only read the rules once so I'm still not sure of some things.

**Comment by hitcherland** [comment]
If you're making changes, use the "development branch", which has several "en.json" files, spread all over the place. Once I've backported your additions, there will be "es.json" files in the same directories!

**Comment by jesberpen** [comment]
Ok, great! I will check that out then. Awesome work with the system in any case, it was very easy to translate, simple but quite effective at having everything there :)

**Comment by hitcherland** [comment]
And we're done, v0.3.16 adds in your Spanish translation!
