### ISSUE TITLE
Tags don't display properly

### ISSUE THREAD

**Issue by JGelfand** [hitcherland/FoundryVTT-Heart#19]
If you drag and drop tags onto e.g. equipment they don't display correctly. Instead of e.g. Brutal it will display tag.tag.brutal.name.name.
The fix is pretty straightforward, in places where you're calling {{localizeHeart "tag" tag.name "name"}}, call {{localizeHeart tag.name}} instead.

I'll attach a modified version of heart.js that seems to work (edited and plopped it into Data/systems/heart)
[heart.txt](https://github.com/hitcherland/FoundryVTT-Heart/files/8145913/heart.txt)
(had to rename b/c git doesn't want me attaching js)

**Comment by hitcherland** [comment]
As I mentioned in the pull request, I have a fix for this that I'll be submitting soon, once I either finish ancestries or disentangle the changes from it.

**Comment by hitcherland** [comment]
That should fix it!
