### ISSUE TITLE
Tags displayed incorrectly in resource preview

### ISSUE THREAD

**Issue by weavejester** [hitcherland/FoundryVTT-Heart#21]
In the character sheet, resources with a tag display incorrectly:

<img width="504" alt="Screenshot 2022-04-30 at 21 39 49" src="https://user-images.githubusercontent.com/8780/166121935-35c8dc0c-43b9-4581-ad48-1b9e11c3d377.png">

It looks like this is because of extra "tag" and "name" string literals in the preview template:

https://github.com/hitcherland/FoundryVTT-Heart/blob/f151cb84d7775ff17e82e94162cbcb508ca6ce1b/src/items/resource/preview.html#L6

**Comment by hitcherland** [comment]
Ah, whoops. Fixed in 0.4.3!
