### ISSUE TITLE
Check and Stress Rolls not displaying in chat log in 0.4.3 and 0.4.4

### ISSUE THREAD

**Issue by weavejester** [hitcherland/FoundryVTT-Heart#24]
When rolling for a check or rolling for stress, either with the macros or the buttons on the character sheet, the dice roll result doesn't appear in the chat log:

![image](https://user-images.githubusercontent.com/8780/168898924-68c4cb05-f715-47b1-8b66-4acec1a1beaa.png)

This appears to affect both 0.4.4 and 0.4.3 (I downgraded until I hit 0.4.2, where it worked).

**Comment by weavejester** [comment]
My guess is that it was broken by be5ac848e0308e38d31c1516dda328612c6492cc.

**Comment by hitcherland** [comment]
You're absolutely right, I've been battling with this hack and getting rollable tables working. I'm working on a fix now.

**Comment by hitcherland** [comment]
Should be fixed in v0.4.5! It was a simple fix!
