### ISSUE TITLE
Deep Apiarist values Flipped for Resource and Hive Tool

### ISSUE THREAD

**Issue by stuttste** [hitcherland/FoundryVTT-Heart#26]
Heartsbloom Rose in a glass jar should be a D6 while Hive Tool should be a D4

https://github.com/hitcherland/FoundryVTT-Heart/blob/fb5ba1b0f1ac3d52f7d3c56a2e831b5d294fb2e7/pack-data/classes/classes.yaml#L351

**Comment by hitcherland** [comment]
fixed in v0.4.7
