### ISSUE TITLE
Foundry VTT v10 Support

### ISSUE THREAD

**Issue by bluefroguk1** [hitcherland/FoundryVTT-Heart#41]
Hi
I'm getting compatibility errors when running FVTT v10 with Heart installed:

setup.js:145 [heart] The system "heart" is using "author" which is deprecated in favor of "authors"
setup.js:145 [heart] The system "heart" is using the old flat core compatibility fields which are deprecated in favor of the new "compatibility" object
setup.js:145 [heart] The system "heart" is using "name" which is deprecated in favor of "id"

**Comment by hitcherland** [comment]
Thanks for letting me know! While it shouldn't cause any problems (other than warnings), I'll get to work on a fix shortly.

**Comment by funzymunzy** [comment]
I have the same errors still, and it grey screens(nothing loads at all) for me. On version 10.286 at the moment.

**Comment by Orphansmith** [comment]
I'm also having the same issue. Is an update still in the works?

**Comment by hitcherland** [comment]
Hey, apologies for the delay in responding. This update is still planned, but it turns out it needs a major rework of the underlying classes, so it won't be a quick job. I can't give an ETA on this because my availability is sporadic

**Comment by Orphansmith** [comment]
Cool, thankfully I was able to back up my world.

**Comment by hitcherland** [comment]
Thanks to whitespine, we got a fix in early, should be out with v0.5.0
