### ISSUE TITLE
[Suggestion] Fallout Categories on Item Sheets

### ISSUE THREAD

**Issue by CyricPL** [hitcherland/FoundryVTT-Heart#53]
It would be very helpful if Fallout items had an attribute to indicate if they are Minor/Major/Critical. Another nice to have would be tags related to Stress type, so for example a given Fallout item would indicate if it is "Minor / Fortune, Supplies"

Edit: To clarify, I realize that the major/minor/critical is contained somewhere in the data of the item but it doesn't seem to display on the item sheet.

**Comment by Wigginns** [comment]
Addressed in https://github.com/hitcherland/FoundryVTT-Heart/pull/54
