### ISSUE TITLE
Unnesesary items in Items tab

### ISSUE THREAD

**Issue by Robak132** [hitcherland/FoundryVTT-Heart#59]
There is a weird bug: When you copy items on sheet or copy them between them, you save it to Items tab in world. Can you do something with it?

**Comment by hitcherland** [comment]
I'd guess that you didn't set the item as "temporary" when creating the
children somewhere. Should be a very small fix if you can find the spot.

**Comment by hitcherland** [comment]
This is fixed in v0.8.4+
