### ISSUE TITLE
Non-item equipment, beats etc. don't show up in newest version

### ISSUE THREAD

**Issue by whitespine** [hitcherland/FoundryVTT-Heart#6]
The player characcter sheets seem to have lost the ability to properly show any non-item elements.

Taking a peek at the html, I see `<div class="editor-content" data-edit="{{description_path}}"></div>`. This seems like its handlebars failing to render this `description_path`?

**Comment by hitcherland** [comment]
Can I ask what version of foundry vtt you are running? I can't see on my end

**Comment by whitespine** [comment]
Foundry ver 0.8.9
Heart ver 0.3.11

For better context, I am referring specifically to the textboxes toggled by "Show text boxes before item lists". Editing and saving them, the content just disappears.

**Comment by hitcherland** [comment]
Sorry for the long delay, it's fixed now in v0.3.12
