### ISSUE TITLE
Character sheets are not synchronizing in real time for GM or Player

### ISSUE THREAD

**Issue by Glaycion** [hitcherland/FoundryVTT-Heart#62]
When trying to activate abilities (toggle them so that they appear in the character sheet itself) in the class sheet, the changes are not synchronized in real time for the GM or player. If you open the class sheet and activate any abilities or add new resources or equipment, the other side (GM or player) won't see the changes, but they are only displayed for the side that makes the changes. You have to reload the page, after which the changes will be displayed for the other side. The same interaction with tags, even if you try to add tags not from the class sheet, but to existing equipment and resources. I didn't check the landmark/delve/adversaries sheet's, but I'm guessing it'll be the same there.

**Comment by hitcherland** [comment]
I can't see myself, using firefox or chrome (on windows). 

- What OS & Browser are you using?
- Does this happen when you have two tabs open as two different users?
- If you open the developer console (press F12), do you see any errors that look somewhat relevant?

**Comment by hitcherland** [comment]
Ah this is hosted on your own machine, not some remote server? I didn't try that yet. I assume you don't have this problem with other systems?

**Comment by hitcherland** [comment]
Ahhh i finally was able to see this happening for myself, and this is fixed in 0.8.6 (to my knowledge).
