### ISSUE TITLE
Adding tags to a character's equipment or resources is not synchronizing correctly

### ISSUE THREAD

**Issue by Glaycion** [hitcherland/FoundryVTT-Heart#65]
Same as in 0.8.5 abilities were not synchronizing, **equipment and resources** **tags** are still not displaying for players after editing in 0.8.7. Regardless of dragging and dropping tags or adding new ones using the button "+ Add Tag", they will not be displayed on the player character sheet. Same goes for adding nested abilities to existing ones. Still have to reload the page for the changes to be visible. My _bandaid_ fix is to edit an item or resource on my private GM character sheet, where all changes are applied in real time, then I can drag the modified item or resource to the player character sheet, only then the changes will be visible for player.

**Comment by hitcherland** [comment]
Should be fixed as of 0.8.8!
