### ISSUE TITLE
Empty Compendium folders

### ISSUE THREAD

**Issue by taborlin99** [hitcherland/FoundryVTT-Heart#67]
Hello. I might just be missing something, but I downloaded this system on foundry, and all compendiums are empty. 

![look_at_these_folders](https://github.com/hitcherland/FoundryVTT-Heart/assets/139376477/50a28458-ed96-4d51-be39-ae63f3a5e953)

Did I just mess up installation? Please let me know where I went wrong <3

**Comment by hitcherland** [comment]
Oh that's concerning! I won't be able to look into this for at least a few days, could you tell me what version of foundry you're using, and the version of Heart that is listed (i assume it's the latest, but better to be sure)?

**Comment by taborlin99** [comment]
> Oh that's concerning! I won't be able to look into this for at least a few days, could you tell me what version of foundry you're using, and the version of Heart that is listed (i assume it's the latest, but better to be sure)?

SORRY I am just dumb, my foundry version was like a year out of date. Thanks for all the work you do!!!
