### ISSUE TITLE
[Suggestion] Merge all localisation files to one folder/file

### ISSUE THREAD

**Issue by Robak132** [hitcherland/FoundryVTT-Heart#69]
Currently, localisation tags are spread across the project with each module having own localisation file. This solution makes translating more difficult because you have to search for files in multiple places. I would suggest moving them to one localisation folder. Also I would recommend checking if there are no tag duplicates between them or tags that can be easily merged.

**Comment by Robak132** [comment]
Duplicate example:
Tag `"heart.resistance.label-single": "Resistance"` is defined in:
-  `src/lang/en.json`, line 51
-  `src/actors/adversary/lang/en.json`, line 16
-  `src/actors/character/lang/en.json`, line 11
All this occurences can be unified to just one.

I can do this unification by myself, while I will making Polish localisation. But I want to discuss this issue with maintainers to make sure that won't be rejected on merge.

**Comment by Wigginns** [comment]
Seems like a good step to me. I'm not familiar enough with localization to really know why it was done the way it is now but that does seem like it'd be easier to maintain and add translations to overtime.

**Comment by hitcherland** [comment]
That's just an idiosyncrasy of when i was putting it together piece by piece, but it's not simple now it's basically complete. By all means unify away!

**Comment by hitcherland** [comment]
This was done as of a few commits ago
