### ISSUE TITLE
Rolls show non-localized strings

### ISSUE THREAD

**Issue by whitespine** [hitcherland/FoundryVTT-Heart#7]
![image](https://user-images.githubusercontent.com/16845226/132265255-ba5a65bd-05b3-45d3-ba94-bb560484efbe.png)

Don't have any idea what the FH... thing is

**Comment by hitcherland** [comment]
The FH thing is, I guess, the id of the character you're rolling? What
version of Foundry VTT are you running, what version of Heart?

**Comment by whitespine** [comment]
Foundry ver 0.8.9
Heart ver 0.3.11

**Comment by hitcherland** [comment]
Sorry for the big delay! I've reproduced your issue, and I'm fixing it now.

**Comment by hitcherland** [comment]
Fixed in v0.3.12!
