### ISSUE TITLE
Request: Add a button to character sheet items to paste a text summary of equipment/resources/abilities/etc

### ISSUE THREAD

**Issue by stevewaretester** [hitcherland/FoundryVTT-Heart#73]
Hi guys, been using this tool for a few sessions of Heart, and it's fantastic, but often we need to display information to each other eg. the Hounds "Forwarned and Forearmed" feature - I would love to show that to people so they know what the feature does as it influences them!

This would be a good general feature though to share info.

I see this being an additional button on the lines in the character sheet, eg:

![image](https://github.com/hitcherland/FoundryVTT-Heart/assets/4118343/31702f41-1b3a-46ce-bd17-e0206dc16e74)

**Comment by hitcherland** [comment]
Typically this can be done by dragging the item into the chat box, but because of the weird way i've implemented nested items that is broken here. I really want to change this, but as that'll be a long fix, I'll add a workaround shortly.
