### ISSUE TITLE
Unable to Update Foundry to Version 0.9.0 on MacOS - Error Occurs and Ongoing Campaign at Risk

### ISSUE THREAD

**Issue by filipehb** [hitcherland/FoundryVTT-Heart#78]
I want to update and can't; I have an ongoing campaign and I'm afraid to uninstall and reinstall and lose the game world; Foundry recognizes that version 0.9.0 exists and that the system is installed, but when I try to update, this error occurs.

OS: MacOS

![image](https://github.com/user-attachments/assets/e756733d-b828-4c30-8f18-2ffad6fbd5e3)

**Comment by hitcherland** [comment]
Major apologies! This should work in place now, if you retry the update. Let me know if it doesn't, I can bump the version by 1 fairly quickly.

On the plus side, if you uninstall a system, the worlds that rely on it don't get deleted, they just become unusable (until you reinstall the system).
