### ISSUE TITLE
Items can't be moved

### ISSUE THREAD

**Issue by Devilscryer** [hitcherland/FoundryVTT-Heart#79]
first of all thanks for updating to V12 :) 

with the new update items cannot be moved into folders or out of folders.
And missing Icons. There seem to be more broken things with items.

**Comment by hitcherland** [comment]
Hi, could you give me more details? Where were you dragging to/from? What were you dragging?

This isn't thorough, but I was able to drag some equipment from a character sheet to a folder in the items tab and back.

**Comment by Devilscryer** [comment]
hi, sorry for exampe from on folder to the other. (like fallout to major fallout)
![grafik](https://github.com/user-attachments/assets/0f504911-daf2-4747-832e-4d227620f6f0)

furthermore i seem to have problem with editiong items.

![grafik](https://github.com/user-attachments/assets/af7a3739-66c5-42f3-8108-c2dfdd5e9ba4)

i can't change any of the parameters neither if the item is in the character sheet nor if it is not in a sheet

**Comment by Devilscryer** [comment]
Well I noticed if I try to edit an item the icon in the sidebar changes shortly to the icon of the type. Afterwards it changes back to the default icon of foundry (as you can see on the screenshot)
