### ISSUE TITLE
Feature Request - Fold Beats on Calling sheet

### ISSUE THREAD

**Issue by funkybrain** [hitcherland/FoundryVTT-Heart#8]
Hey! Hope its ok to use the issue tracker as a feature request. The module is frankly amazing. One small QoL would be to fold the long list of Minor and Major Beats on the Calling sheet. It's nice to populate the sheet with every available beat so PCs know what is available to them, but you invariably end up with a long list to scroll in order to get to Major or Zenith beats.

**Comment by hitcherland** [comment]
It's definitely okay, thanks for adding it. I'll put it on my todo list, but should be an easy one!

**Comment by hitcherland** [comment]
Exists now in v0.3.12 (and I added something similar for the classes ability list).

**Comment by funkybrain** [comment]
Works great thank you! The orientation of the arrow seems counter-intuitive to me, but I think it's a matter of personal taste, much like 'natural scrolling direction' can be ;)

**Comment by hitcherland** [comment]
Very fair, I'll have a look at some alternatives for the next release
