### ISSUE TITLE
Auto-roll stress and fallout (post-migration to Foundry v.12)

### ISSUE THREAD

**Issue by mtill14** [hitcherland/FoundryVTT-Heart#84]
In Heart system version 0.8.9 (playing in Foundry v11.315), we were able to auto-roll stress, apply the stress, and check for fallout from the symbols in the chat log.
Since upgrading to Foundry v12.331 and Heart v0.9.2, this functionality no longer works and the buttons seem to do nothing.

Would it be possible to re-establish this functionality?

**Comment by hitcherland** [comment]
Should be fixed in 0.9.4
