### ISSUE TITLE
Toggle sliders/buttons for activating/deactivating/completing beats (post-migration to Foundry v.12)

### ISSUE THREAD

**Issue by mtill14** [hitcherland/FoundryVTT-Heart#85]
In Heart system version 0.8.9 (playing in Foundry v11.315), we were able to use toggles/sliders to manage beats from the character's embedded calling. There was also a button to mark the beat complete
Since upgrading to Foundry v12.331 and Heart v0.9.2, these buttons are no longer there. They do appear the same way on most abilities (at least, have not been able to verify extensively), but not on beats.

**Comment by hitcherland** [comment]
Should be fixed in 0.9.4

**Comment by Rimeson** [comment]
For some reason it's not working on my end, in 0.9.4. The Callings sheet has Complete and Activate buttons for beats, but they don't appear on character sheets. Attached a clip to show what I mean.

https://github.com/user-attachments/assets/ccac661a-87fc-4eab-8f70-39d9799cb6a7
